INSERT INTO users(email, password) VALUES('test', 'test');

INSERT INTO items(item_name, users_id, type, img) VALUES('Canned Tomoes', 1, 'h', 'tomatoes');
INSERT INTO items(item_name, users_id, type, img) VALUES('Crackers', 1, 'h', 'crackers');
INSERT INTO items(item_name, users_id, type, img) VALUES('Granola', 1, 'h', 'granola');
INSERT INTO items(item_name, users_id, type, img) VALUES('Cooking Water', 1, 'h', 'cookwater');
INSERT INTO items(item_name, users_id, type, img) VALUES('First Aid', 1, 'h', 'firstaid');
INSERT INTO items(item_name, users_id, type, img) VALUES('Flashlight', 1, 'h', 'flashlight');
INSERT INTO items(item_name, users_id, type, img) VALUES('Can Opener', 1, 'h', 'canopener');
INSERT INTO items(item_name, users_id, type, img) VALUES('Whistle', 1, 'h', 'whistle');
INSERT INTO items(item_name, users_id, type, img) VALUES('Radio', 1, 'h', 'radio');
INSERT INTO items(item_name, users_id, type, img) VALUES('Flare', 1, 'h', 'flare');
INSERT INTO items(item_name, users_id, type, img) VALUES('Documents', 1, 'h', 'documents');
INSERT INTO items(item_name, users_id, type, img) VALUES('Drinking Water', 1, 'h', 'drinkwater');
INSERT INTO items(item_name, users_id, type, img) VALUES('Spare Keys', 1, 'h', 'sparekeys');
INSERT INTO items(item_name, users_id, type, img) VALUES('Candles', 1, 'h', 'candles');
INSERT INTO items(item_name, users_id, type, img) VALUES('Clothes', 1, 'h', 'clothes');
INSERT INTO items(item_name, users_id, type, img) VALUES('Snow Brush', 1, 'h', 'snowbrush');
INSERT INTO items(item_name, users_id, type, img) VALUES('Medication', 1, 'h', 'medication');
INSERT INTO items(item_name, users_id, type, img) VALUES('Money', 1, 'h', 'money');
INSERT INTO items(item_name, users_id, type, img) VALUES('ID Copy', 1, 'h', 'idcopy');
INSERT INTO items(item_name, users_id, type, img) VALUES('Shovel', 1, 'h', 'shovel');
INSERT INTO items(item_name, users_id, type, img) VALUES('Matches', 1, 'h', 'matches');